title: CDSC CoSyML
email: your.email@example.com
description: >-
  Academic homepage for research, teaching, publications, and projects.
baseurl: ""
url: "https://cdsc-cosyml.github.io/"
markdown: kramdown
permalink: pretty
plugins: []
